name: Benchmark

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Install k6
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg ca-certificates
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/k6.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      # 3. Start services
      - name: Build and start services
        run: docker compose up -d --build

      # show logs
      - name: Show logs
        run: docker compose logs app

      # # debug again
      # - name: Test curl
      #   run: |
      #     curl -v http://localhost:3000
      #     docker compose logs --tail=10 app

      # 4. Debug containers (optional tapi penting buat validasi)
      - name: Debug app startup
        run: |
          echo "=== Docker processes ==="
          docker ps -a

          echo "=== App logs ==="
          docker compose logs app

          echo "=== DB logs ==="
          docker compose logs db

          echo "=== App health status ==="
          docker inspect --format='{{json .State}}' $(docker compose ps -q app)

      # 5. Wait for services ready
      - name: Wait for services
        run: |
          echo "Waiting for app..."
          for i in $(seq 1 60); do
            if curl -sf --ipv4 http://localhost:3000 > /dev/null 2>&1; then
              echo "App ready!"
              break
            fi
            echo "Attempt $i/60 - not ready yet..."
            docker compose logs --tail=3 app
            if [ $i -eq 60 ]; then
              echo "TIMEOUT"
              docker compose logs app
              docker compose logs db
              exit 1
            fi
            sleep 5
          done

          echo "Waiting for Prometheus..."
          for i in $(seq 1 20); do
            if curl -sf http://localhost:9090/-/ready > /dev/null 2>&1; then
              echo "Prometheus ready!"
              break
            fi
            echo "Attempt $i/20..."
            sleep 3
          done
      # 6. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 7. Install dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # 8. Run load test (k6 via python)
      - name: Run benchmark test
        run: python metrics/run-test.py

      # 9. Kasih waktu Prometheus scrape data terakhir
      - name: Wait before exporting metrics
        run: sleep 10

      # 10. Export metrics ke CSV
      - name: Export metrics
        run: python metrics/export-metrics.py

      # 11. Upload hasil benchmark
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            *.csv
            *.png
